### ISSUE TITLE
It's not working on flutter web

### ISSUE THREAD

**Issue by avenwu** [dannyvalente/flutter_selectable_text#7]
It's not working on flutter web,  similar to the framework provided SelectableText, unable to copy

`flutter_selectable_text: ^0.3.1`

```dart
import 'package:flutter_selectable_text/flutter_selectable_text.dart' as select;

select.SelectableText('copy the content');
```

**Comment by dannyvalente** [comment]
This plugin was created before the flutter sdk had its own version. Please use the built in version. I don't know if it exists for flutter web though.
